[shell]
program = "/bin/zsh"
args = ["-l"]
# working_directory = "~/"

[font]
normal = { family = "Hack", style = "Regular" }
size = 15.0
offset = { x = 0, y = 1 }

# Colors (One Dark)
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'

[colors.cursor]
text = "#5C6370"
cursor = "#5C6370"

[cursor.style]
shape = "Block"
blinking = "Never"

[mouse]
bindings = [
  { mouse = "Right", action = "Paste" },
]


[window]
opacity = 0.85
blur = true
startup_mode = "Maximized"
title = "Terminal"
