[general]
copy-command = "wl-copy --type image/png"
actions-on-enter = ["save-to-clipboard"]
save-after-copy = false
initial-tool = "arrow"
corner-roundness = 12
early-exit = false
default-hide-toolbars = false
disable-notifications = true
output-filename = "~/Pictures/Screenshots/screenshot-%Y%m%d_%H%M%S.png"
